name: Publish Release

on:
  release:
    types:
      - created

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: get_tag
        name: Get Tag
        env:
          GITHUB_HEAD_REF: $${{ github.head_ref }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
        run: |
          if [ "${{ github.event.inputs.version }}" = "" ]
          then
            TAG=$(jq --raw-output '.release.tag_name' $GITHUB_EVENT_PATH)
          else
            TAG=${{ github.event.inputs.version }}
          fi
          
          echo ::set-output name=TAG::$TAG
      - name: Build Godot Project
        id: build
        uses: josephbmanley/build-godot-action@v1.4.0
        with:
          name: TetraForce
          preset: linux
          projectDir: '.'
          debugMode: 'true'
      - name: Push Tag to GitHub Package
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: "docker.pkg.github.com/fornclake/tetraforce"
          BUILD_PATH: "."
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "tetraforce"
          TAG_NAME: ${{ steps.get_tag.outputs.TAG }}
          LATEST: "true"
  godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, osx, win32, win64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        env:
          PLATFORM: ${{ matrix.platform }}
        run: |
          if [ "$PLATFORM" = "win32" ] || [ "$PLATFORM" = "win64" ] ; then
            echo "::set-env name=EXPORT_SUFFIX::.exe"
          fi
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.0
        with:
          name: TetraForce${{ env.EXPORT_SUFFIX }}
          preset: ${{ matrix.platform }}
          projectDir: '.'
      # In the future a push to itch or other platform would go here